"E:\Android\Android Studio\jbr\bin\java.exe" "-javaagent:E:\Android\Android Studio\lib\idea_rt.jar=50935:E:\Android\Android Studio\bin" -Dfile.encoding=UTF-8 -classpath E:\Android\SDK\platforms\android-28\android.jar;E:\Android\SDK\platforms\android-28\data\res;D:\StudioProject\svgaplayer-android-glide_feature\library\build\intermediates\javac\debug\classes;D:\StudioProject\svgaplayer-android-glide_feature\library\build\tmp\kotlin-classes\debug;D:\StudioProject\svgaplayer-android-glide_feature\library\build\tmp\kapt3\classes\debug;D:\StudioProject\svgaplayer-android-glide_feature\library\build\intermediates\compile_r_class_jar\debug\R.jar;D:\StudioProject\svgaplayer-android-glide_feature\library\build\generated\res\resValues\debug;C:\Users\lenovo\.gradle\caches\transforms-3\e053ed084cc05dd7afe055324f5a4036\transformed\glide-4.15.1\AndroidManifest.xml;C:\Users\lenovo\.gradle\caches\transforms-3\e053ed084cc05dd7afe055324f5a4036\transformed\glide-4.15.1\res;C:\Users\lenovo\.gradle\caches\transforms-3\e053ed084cc05dd7afe055324f5a4036\transformed\glide-4.15.1\jars\classes.jar;C:\Users\lenovo\.gradle\caches\transforms-3\dac8dd75c3f3f6bc71f550cb534a83be\transformed\gifdecoder-4.15.1\AndroidManifest.xml;C:\Users\lenovo\.gradle\caches\transforms-3\dac8dd75c3f3f6bc71f550cb534a83be\transformed\gifdecoder-4.15.1\jars\classes.jar;C:\Users\lenovo\.gradle\caches\transforms-3\0850634e469edf6a2c48d3551f08ad1c\transformed\fragment-1.3.6\AndroidManifest.xml;C:\Users\lenovo\.gradle\caches\transforms-3\0850634e469edf6a2c48d3551f08ad1c\transformed\fragment-1.3.6\jars\classes.jar;C:\Users\lenovo\.gradle\caches\transforms-3\0850634e469edf6a2c48d3551f08ad1c\transformed\fragment-1.3.6\res;C:\Users\lenovo\.gradle\caches\transforms-3\9926d4e24c06af65f30d162c52ec4ad0\transformed\core-1.2.0\jars\classes.jar;C:\Users\lenovo\.gradle\caches\transforms-3\9926d4e24c06af65f30d162c52ec4ad0\transformed\core-1.2.0\res;C:\Users\lenovo\.gradle\caches\transforms-3\9926d4e24c06af65f30d162c52ec4ad0\transformed\core-1.2.0\AndroidManifest.xml;C:\Users\lenovo\.gradle\caches\transforms-3\cfaf873e7ee0c1a248afc8b6bcb71bf7\transformed\lifecycle-runtime-2.3.1\jars\classes.jar;C:\Users\lenovo\.gradle\caches\transforms-3\cfaf873e7ee0c1a248afc8b6bcb71bf7\transformed\lifecycle-runtime-2.3.1\res;C:\Users\lenovo\.gradle\caches\transforms-3\cfaf873e7ee0c1a248afc8b6bcb71bf7\transformed\lifecycle-runtime-2.3.1\AndroidManifest.xml;C:\Users\lenovo\.gradle\caches\transforms-3\090576a75d4623bb4cbcfa01afb3083d\transformed\versionedparcelable-1.1.0\jars\classes.jar;C:\Users\lenovo\.gradle\caches\transforms-3\090576a75d4623bb4cbcfa01afb3083d\transformed\versionedparcelable-1.1.0\AndroidManifest.xml;C:\Users\lenovo\.gradle\caches\transforms-3\a25f9206d7ea75f694c1085d0061a773\transformed\viewpager-1.0.0\jars\classes.jar;C:\Users\lenovo\.gradle\caches\transforms-3\a25f9206d7ea75f694c1085d0061a773\transformed\viewpager-1.0.0\AndroidManifest.xml;C:\Users\lenovo\.gradle\caches\transforms-3\1666a217500a4a089e2acf277f6e76fe\transformed\customview-1.0.0\AndroidManifest.xml;C:\Users\lenovo\.gradle\caches\transforms-3\1666a217500a4a089e2acf277f6e76fe\transformed\customview-1.0.0\jars\classes.jar;C:\Users\lenovo\.gradle\caches\transforms-3\f9000f71dbea4023d505cbb0097886d0\transformed\loader-1.0.0\jars\classes.jar;C:\Users\lenovo\.gradle\caches\transforms-3\f9000f71dbea4023d505cbb0097886d0\transformed\loader-1.0.0\AndroidManifest.xml;C:\Users\lenovo\.gradle\caches\transforms-3\84bbf98b3dde0c29df7bfa42a728ee31\transformed\lifecycle-livedata-2.0.0\jars\classes.jar;C:\Users\lenovo\.gradle\caches\transforms-3\84bbf98b3dde0c29df7bfa42a728ee31\transformed\lifecycle-livedata-2.0.0\AndroidManifest.xml;C:\Users\lenovo\.gradle\caches\transforms-3\a0eaf6f6bcf289080cda4bb22e395e39\transformed\core-runtime-2.1.0\AndroidManifest.xml;C:\Users\lenovo\.gradle\caches\transforms-3\a0eaf6f6bcf289080cda4bb22e395e39\transformed\core-runtime-2.1.0\jars\classes.jar;C:\Users\lenovo\.gradle\caches\transforms-3\b3bc29d7233f00d2b9e4c5d8f0659180\transformed\lifecycle-livedata-core-2.3.1\jars\classes.jar;C:\Users\lenovo\.gradle\caches\transforms-3\b3bc29d7233f00d2b9e4c5d8f0659180\transformed\lifecycle-livedata-core-2.3.1\AndroidManifest.xml;C:\Users\lenovo\.gradle\caches\transforms-3\6b13fc83192373bc264179d79946eb26\transformed\lifecycle-viewmodel-2.3.1\jars\classes.jar;C:\Users\lenovo\.gradle\caches\transforms-3\6b13fc83192373bc264179d79946eb26\transformed\lifecycle-viewmodel-2.3.1\AndroidManifest.xml;C:\Users\lenovo\.gradle\caches\transforms-3\6b13fc83192373bc264179d79946eb26\transformed\lifecycle-viewmodel-2.3.1\res;C:\Users\lenovo\.gradle\caches\transforms-3\959da36a6607ab7a65e58ff4d5f85c4b\transformed\activity-1.2.4\jars\classes.jar;C:\Users\lenovo\.gradle\caches\transforms-3\959da36a6607ab7a65e58ff4d5f85c4b\transformed\activity-1.2.4\AndroidManifest.xml;C:\Users\lenovo\.gradle\caches\transforms-3\9f30f0a381ac3a8c3503afaf8bb833d2\transformed\savedstate-1.1.0\jars\classes.jar;C:\Users\lenovo\.gradle\caches\transforms-3\9f30f0a381ac3a8c3503afaf8bb833d2\transformed\savedstate-1.1.0\res;C:\Users\lenovo\.gradle\caches\transforms-3\9f30f0a381ac3a8c3503afaf8bb833d2\transformed\savedstate-1.1.0\AndroidManifest.xml;C:\Users\lenovo\.gradle\caches\transforms-3\5c38c8f55fc757a9b2695ba9607a7540\transformed\lifecycle-viewmodel-savedstate-2.3.1\jars\classes.jar;C:\Users\lenovo\.gradle\caches\transforms-3\5c38c8f55fc757a9b2695ba9607a7540\transformed\lifecycle-viewmodel-savedstate-2.3.1\AndroidManifest.xml;C:\Users\lenovo\.gradle\caches\transforms-3\ccdf9d711c35e5c384f45afd9d8ff36a\transformed\annotation-experimental-1.0.0\jars\classes.jar;C:\Users\lenovo\.gradle\caches\transforms-3\ccdf9d711c35e5c384f45afd9d8ff36a\transformed\annotation-experimental-1.0.0\AndroidManifest.xml;C:\Users\lenovo\.gradle\caches\transforms-3\ce8cee7d897eab7197d0ec5b39cf71df\transformed\vectordrawable-animated-1.1.0\AndroidManifest.xml;C:\Users\lenovo\.gradle\caches\transforms-3\ce8cee7d897eab7197d0ec5b39cf71df\transformed\vectordrawable-animated-1.1.0\jars\classes.jar;C:\Users\lenovo\.gradle\caches\transforms-3\77e605864a829654bacb1b0a61e96509\transformed\vectordrawable-1.1.0\jars\classes.jar;C:\Users\lenovo\.gradle\caches\transforms-3\77e605864a829654bacb1b0a61e96509\transformed\vectordrawable-1.1.0\AndroidManifest.xml;C:\Users\lenovo\.gradle\caches\transforms-3\0fc41687747ca97f9be3164b502996dd\transformed\interpolator-1.0.0\AndroidManifest.xml;C:\Users\lenovo\.gradle\caches\transforms-3\0fc41687747ca97f9be3164b502996dd\transformed\interpolator-1.0.0\jars\classes.jar;C:\Users\lenovo\.gradle\caches\transforms-3\73cd8fe722045ad601a7c6fcbbe15834\transformed\exifinterface-1.3.3\jars\classes.jar;C:\Users\lenovo\.gradle\caches\transforms-3\73cd8fe722045ad601a7c6fcbbe15834\transformed\exifinterface-1.3.3\AndroidManifest.xml;C:\Users\lenovo\.gradle\caches\transforms-3\c3c8c344a95892cab1eab3a9d9f50dbe\transformed\tracing-1.0.0\jars\classes.jar;C:\Users\lenovo\.gradle\caches\transforms-3\c3c8c344a95892cab1eab3a9d9f50dbe\transformed\tracing-1.0.0\AndroidManifest.xml;C:\Users\lenovo\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-android-extensions-runtime\1.7.20\4258071243cf01165f08c0c5a891a720cf8a607a\kotlin-android-extensions-runtime-1.7.20.jar;C:\Users\lenovo\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-stdlib\1.7.20\726594ea9ba2beb2ee113647fefa9a10f9fabe52\kotlin-stdlib-1.7.20.jar;C:\Users\lenovo\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-stdlib-common\1.7.20\e15351bdaf9fa06f009be5da7a202e4184f00ae3\kotlin-stdlib-common-1.7.20.jar;C:\Users\lenovo\.gradle\caches\modules-2\files-2.1\org.jetbrains\annotations\13.0\919f0dfe192fb4e063e7dacadee7f8bb9a2672a9\annotations-13.0.jar;C:\Users\lenovo\.gradle\caches\modules-2\files-2.1\com.squareup.wire\wire-runtime\3.7.0\fce08da6dd43acfc9f3a5e946a7be32bdc08066f\wire-runtime-jvm-3.7.0.jar;C:\Users\lenovo\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-stdlib-jdk8\1.4.10\998caa30623f73223194a8b657abd2baec4880ea\kotlin-stdlib-jdk8-1.4.10.jar;C:\Users\lenovo\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-stdlib-jdk7\1.7.20\2a729aa8763306368e665e2b747abd1dfd29b9d5\kotlin-stdlib-jdk7-1.7.20.jar;C:\Users\lenovo\.gradle\caches\modules-2\files-2.1\com.squareup.okio\okio\2.8.0\49b64e09d81c0cc84b267edd0c2fd7df5a64c78c\okio-jvm-2.8.0.jar;C:\Users\lenovo\.gradle\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-reflect\1.7.20\12b2501e33bb6373e8e347c86d85481863629381\kotlin-reflect-1.7.20.jar;C:\Users\lenovo\.gradle\caches\modules-2\files-2.1\androidx.annotation\annotation\1.3.0\21f49f5f9b85fc49de712539f79123119740595\annotation-1.3.0.jar;C:\Users\lenovo\.gradle\caches\modules-2\files-2.1\com.github.bumptech.glide\disklrucache\4.15.1\e47ade981aefb5b975382750490d195fa569bbdf\disklrucache-4.15.1.jar;C:\Users\lenovo\.gradle\caches\modules-2\files-2.1\com.github.bumptech.glide\annotations\4.15.1\d3721a4986a833e4ea71126489d12e08964b6f07\annotations-4.15.1.jar;C:\Users\lenovo\.gradle\caches\modules-2\files-2.1\androidx.lifecycle\lifecycle-common\2.3.1\fc466261d52f4433863642fb40d12441ae274a98\lifecycle-common-2.3.1.jar;C:\Users\lenovo\.gradle\caches\modules-2\files-2.1\androidx.arch.core\core-common\2.1.0\b3152fc64428c9354344bd89848ecddc09b6f07e\core-common-2.1.0.jar;C:\Users\lenovo\.gradle\caches\modules-2\files-2.1\androidx.collection\collection\1.1.0\1f27220b47669781457de0d600849a5de0e89909\collection-1.1.0.jar;C:\Users\lenovo\.gradle\caches\modules-2\files-2.1\org.ow2.asm\asm-commons\9.6\f1a9e5508eff490744144565c47326c8648be309\asm-commons-9.6.jar;C:\Users\lenovo\.gradle\caches\modules-2\files-2.1\org.ow2.asm\asm\9.6\aa205cf0a06dbd8e04ece91c0b37c3f5d567546a\asm-9.6.jar;C:\Users\lenovo\.gradle\caches\modules-2\files-2.1\org.ow2.asm\asm-tree\9.6\c0cdda9d211e965d2a4448aa3fd86110f2f8c2de\asm-tree-9.6.jar;C:\Users\lenovo\.gradle\caches\modules-2\files-2.1\org.ow2.asm\asm-util\9.6\f77caf84eb93786a749b2baa40865b9613e3eaee\asm-util-9.6.jar;C:\Users\lenovo\.gradle\caches\modules-2\files-2.1\org.ow2.asm\asm-analysis\9.6\9ce6c7b174bd997fc2552dff47964546bd7a5ec3\asm-analysis-9.6.jar com.svga.glide.ASMPrintKt
package asm.com.svga.glide;
import org.objectweb.asm.AnnotationVisitor;
import org.objectweb.asm.Attribute;
import org.objectweb.asm.ClassReader;
import org.objectweb.asm.ClassWriter;
import org.objectweb.asm.ConstantDynamic;
import org.objectweb.asm.FieldVisitor;
import org.objectweb.asm.Handle;
import org.objectweb.asm.Label;
import org.objectweb.asm.MethodVisitor;
import org.objectweb.asm.Opcodes;
import org.objectweb.asm.RecordComponentVisitor;
import org.objectweb.asm.Type;
import org.objectweb.asm.TypePath;
public class SVGAGlideResourceDelegateDump implements Opcodes {

public static byte[] dump () throws Exception {

ClassWriter classWriter = new ClassWriter(0);
FieldVisitor fieldVisitor;
RecordComponentVisitor recordComponentVisitor;
MethodVisitor methodVisitor;
AnnotationVisitor annotationVisitor0;

classWriter.visit(V1_8, ACC_PUBLIC | ACC_FINAL | ACC_SUPER, "com/svga/glide/SVGAGlideResourceDelegate", "Ljava/lang/Object;Lcom/bumptech/glide/load/engine/Resource<Lcom/svga/glide/SVGAResource;>;", "java/lang/Object", new String[] { "com/bumptech/glide/load/engine/Resource" });

{
annotationVisitor0 = classWriter.visitAnnotation("Lkotlin/Metadata;", true);
annotationVisitor0.visit("mv", new int[] {1,7,1});
annotationVisitor0.visit("k", new Integer(1));
annotationVisitor0.visit("xi", new Integer(48));
{
AnnotationVisitor annotationVisitor1 = annotationVisitor0.visitArray("d1");
annotationVisitor1.visit(null, "\u0000*\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0018\u0002\n\u0002\u0008\u0003\n\u0002\u0010\u000e\n\u0002\u0008\u0002\n\u0002\u0018\u0002\n\u0000\n\u0002\u0010\u0008\n\u0000\n\u0002\u0010\u0002\n\u0000\u0018\u00002\u0008\u0012\u0004\u0012\u00020\u00020\u0001B\r\u0012\u0006\u0010\u0003\u001a\u00020\u0002\u00a2\u0006\u0002\u0010\u0004J\u0008\u0010\u0007\u001a\u00020\u0002H\u0016J\u000e\u0010\u0008\u001a\u0008\u0012\u0004\u0012\u00020\u00020\u0009H\u0016J\u0008\u0010\n\u001a\u00020\u000bH\u0016J\u0008\u0010\u000c\u001a\u00020\rH\u0016R\u000e\u0010\u0005\u001a\u00020\u0006X\u0082D\u00a2\u0006\u0002\n\u0000R\u000e\u0010\u0003\u001a\u00020\u0002X\u0082\u0004\u00a2\u0006\u0002\n\u0000\u00a8\u0006\u000e");
annotationVisitor1.visitEnd();
}
{
AnnotationVisitor annotationVisitor1 = annotationVisitor0.visitArray("d2");
annotationVisitor1.visit(null, "Lcom/svga/glide/SVGAGlideResourceDelegate;");
annotationVisitor1.visit(null, "Lcom/bumptech/glide/load/engine/Resource;");
annotationVisitor1.visit(null, "Lcom/svga/glide/SVGAResource;");
annotationVisitor1.visit(null, "resource");
annotationVisitor1.visit(null, "(Lcom/svga/glide/SVGAResource;)V");
annotationVisitor1.visit(null, "TAG");
annotationVisitor1.visit(null, "");
annotationVisitor1.visit(null, "get");
annotationVisitor1.visit(null, "getResourceClass");
annotationVisitor1.visit(null, "Ljava/lang/Class;");
annotationVisitor1.visit(null, "getSize");
annotationVisitor1.visit(null, "");
annotationVisitor1.visit(null, "recycle");
annotationVisitor1.visit(null, "");
annotationVisitor1.visit(null, "com.opensource.svgaplayer");
annotationVisitor1.visitEnd();
}
annotationVisitor0.visitEnd();
}
{
fieldVisitor = classWriter.visitField(ACC_PRIVATE | ACC_FINAL, "resource", "Lcom/svga/glide/SVGAResource;", null, null);
{
annotationVisitor0 = fieldVisitor.visitAnnotation("Lorg/jetbrains/annotations/NotNull;", false);
annotationVisitor0.visitEnd();
}
fieldVisitor.visitEnd();
}
{
fieldVisitor = classWriter.visitField(ACC_PRIVATE | ACC_FINAL, "TAG", "Ljava/lang/String;", null, null);
{
annotationVisitor0 = fieldVisitor.visitAnnotation("Lorg/jetbrains/annotations/NotNull;", false);
annotationVisitor0.visitEnd();
}
fieldVisitor.visitEnd();
}
{
methodVisitor = classWriter.visitMethod(ACC_PUBLIC, "<init>", "(Lcom/svga/glide/SVGAResource;)V", null, null);
methodVisitor.visitAnnotableParameterCount(1, false);
{
annotationVisitor0 = methodVisitor.visitParameterAnnotation(0, "Lorg/jetbrains/annotations/NotNull;", false);
annotationVisitor0.visitEnd();
}
methodVisitor.visitCode();
methodVisitor.visitVarInsn(ALOAD, 1);
methodVisitor.visitLdcInsn("resource");
methodVisitor.visitMethodInsn(INVOKESTATIC, "kotlin/jvm/internal/Intrinsics", "checkNotNullParameter", "(Ljava/lang/Object;Ljava/lang/String;)V", false);
methodVisitor.visitVarInsn(ALOAD, 0);
methodVisitor.visitMethodInsn(INVOKESPECIAL, "java/lang/Object", "<init>", "()V", false);
methodVisitor.visitVarInsn(ALOAD, 0);
methodVisitor.visitVarInsn(ALOAD, 1);
methodVisitor.visitFieldInsn(PUTFIELD, "com/svga/glide/SVGAGlideResourceDelegate", "resource", "Lcom/svga/glide/SVGAResource;");
methodVisitor.visitVarInsn(ALOAD, 0);
methodVisitor.visitLdcInsn("SVGAGlideResourceDelegate");
methodVisitor.visitFieldInsn(PUTFIELD, "com/svga/glide/SVGAGlideResourceDelegate", "TAG", "Ljava/lang/String;");
methodVisitor.visitInsn(RETURN);
methodVisitor.visitMaxs(2, 2);
methodVisitor.visitEnd();
}
{
methodVisitor = classWriter.visitMethod(ACC_PUBLIC, "getResourceClass", "()Ljava/lang/Class;", "()Ljava/lang/Class<Lcom/svga/glide/SVGAResource;>;", null);
{
annotationVisitor0 = methodVisitor.visitAnnotation("Lorg/jetbrains/annotations/NotNull;", false);
annotationVisitor0.visitEnd();
}
methodVisitor.visitCode();
methodVisitor.visitLdcInsn(Type.getType("Lcom/svga/glide/SVGAResource;"));
methodVisitor.visitInsn(ARETURN);
methodVisitor.visitMaxs(1, 1);
methodVisitor.visitEnd();
}
{
methodVisitor = classWriter.visitMethod(ACC_PUBLIC, "get", "()Lcom/svga/glide/SVGAResource;", null, null);
{
annotationVisitor0 = methodVisitor.visitAnnotation("Lorg/jetbrains/annotations/NotNull;", false);
annotationVisitor0.visitEnd();
}
methodVisitor.visitCode();
methodVisitor.visitVarInsn(ALOAD, 0);
methodVisitor.visitFieldInsn(GETFIELD, "com/svga/glide/SVGAGlideResourceDelegate", "resource", "Lcom/svga/glide/SVGAResource;");
methodVisitor.visitInsn(ARETURN);
methodVisitor.visitMaxs(1, 1);
methodVisitor.visitEnd();
}
{
methodVisitor = classWriter.visitMethod(ACC_PUBLIC, "getSize", "()I", null, null);
methodVisitor.visitCode();
Label label0 = new Label();
Label label1 = new Label();
Label label2 = new Label();
methodVisitor.visitTryCatchBlock(label0, label1, label2, "java/lang/Throwable");
Label label3 = new Label();
Label label4 = new Label();
Label label5 = new Label();
methodVisitor.visitTryCatchBlock(label3, label4, label5, "java/lang/Throwable");
methodVisitor.visitInsn(ICONST_0);
methodVisitor.visitVarInsn(ISTORE, 1);
methodVisitor.visitLabel(label3);
methodVisitor.visitInsn(NOP);
methodVisitor.visitVarInsn(ALOAD, 0);
methodVisitor.visitFieldInsn(GETFIELD, "com/svga/glide/SVGAGlideResourceDelegate", "resource", "Lcom/svga/glide/SVGAResource;");
methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "com/svga/glide/SVGAResource", "getVideoItem", "()Lcom/opensource/svgaplayer/SVGAVideoEntity;", false);
methodVisitor.visitInsn(DUP);
Label label6 = new Label();
methodVisitor.visitJumpInsn(IFNULL, label6);
methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "com/opensource/svgaplayer/SVGAVideoEntity", "getImageMap$com_opensource_svgaplayer", "()Ljava/util/HashMap;", false);
Label label7 = new Label();
methodVisitor.visitJumpInsn(GOTO, label7);
methodVisitor.visitLabel(label6);
methodVisitor.visitInsn(POP);
methodVisitor.visitInsn(ACONST_NULL);
methodVisitor.visitLabel(label7);
methodVisitor.visitVarInsn(ASTORE, 2);
methodVisitor.visitVarInsn(ALOAD, 2);
methodVisitor.visitInsn(DUP);
Label label8 = new Label();
methodVisitor.visitJumpInsn(IFNULL, label8);
methodVisitor.visitTypeInsn(CHECKCAST, "java/util/Map");
methodVisitor.visitVarInsn(ASTORE, 3);
methodVisitor.visitInsn(ICONST_0);
methodVisitor.visitVarInsn(ISTORE, 4);
methodVisitor.visitVarInsn(ALOAD, 3);
methodVisitor.visitMethodInsn(INVOKEINTERFACE, "java/util/Map", "entrySet", "()Ljava/util/Set;", true);
methodVisitor.visitMethodInsn(INVOKEINTERFACE, "java/util/Set", "iterator", "()Ljava/util/Iterator;", true);
methodVisitor.visitVarInsn(ASTORE, 5);
Label label9 = new Label();
methodVisitor.visitLabel(label9);
methodVisitor.visitVarInsn(ALOAD, 5);
methodVisitor.visitMethodInsn(INVOKEINTERFACE, "java/util/Iterator", "hasNext", "()Z", true);
Label label10 = new Label();
methodVisitor.visitJumpInsn(IFEQ, label10);
methodVisitor.visitVarInsn(ALOAD, 5);
methodVisitor.visitMethodInsn(INVOKEINTERFACE, "java/util/Iterator", "next", "()Ljava/lang/Object;", true);
methodVisitor.visitTypeInsn(CHECKCAST, "java/util/Map$Entry");
methodVisitor.visitVarInsn(ASTORE, 6);
methodVisitor.visitVarInsn(ALOAD, 6);
methodVisitor.visitVarInsn(ASTORE, 7);
methodVisitor.visitInsn(ICONST_0);
methodVisitor.visitVarInsn(ISTORE, 8);
methodVisitor.visitVarInsn(ILOAD, 1);
methodVisitor.visitVarInsn(ALOAD, 7);
methodVisitor.visitMethodInsn(INVOKEINTERFACE, "java/util/Map$Entry", "getValue", "()Ljava/lang/Object;", true);
methodVisitor.visitTypeInsn(CHECKCAST, "android/graphics/Bitmap");
methodVisitor.visitMethodInsn(INVOKESTATIC, "com/bumptech/glide/util/Util", "getBitmapByteSize", "(Landroid/graphics/Bitmap;)I", false);
methodVisitor.visitInsn(IADD);
methodVisitor.visitVarInsn(ISTORE, 1);
methodVisitor.visitInsn(NOP);
methodVisitor.visitJumpInsn(GOTO, label9);
methodVisitor.visitLabel(label10);
methodVisitor.visitInsn(NOP);
Label label11 = new Label();
methodVisitor.visitJumpInsn(GOTO, label11);
methodVisitor.visitLabel(label8);
methodVisitor.visitInsn(POP);
methodVisitor.visitInsn(NOP);
methodVisitor.visitLabel(label4);
methodVisitor.visitJumpInsn(GOTO, label11);
methodVisitor.visitLabel(label5);
methodVisitor.visitVarInsn(ASTORE, 2);
methodVisitor.visitLabel(label0);
methodVisitor.visitInsn(NOP);
methodVisitor.visitVarInsn(ALOAD, 0);
methodVisitor.visitFieldInsn(GETFIELD, "com/svga/glide/SVGAGlideResourceDelegate", "resource", "Lcom/svga/glide/SVGAResource;");
methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "com/svga/glide/SVGAResource", "getImageMapField", "()Lcom/svga/glide/util/ReflectUtils;", false);
methodVisitor.visitInsn(DUP);
Label label12 = new Label();
methodVisitor.visitJumpInsn(IFNULL, label12);
methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "com/svga/glide/util/ReflectUtils", "get", "()Ljava/lang/Object;", false);
methodVisitor.visitTypeInsn(CHECKCAST, "java/util/HashMap");
Label label13 = new Label();
methodVisitor.visitJumpInsn(GOTO, label13);
methodVisitor.visitLabel(label12);
methodVisitor.visitInsn(POP);
methodVisitor.visitInsn(ACONST_NULL);
methodVisitor.visitLabel(label13);
methodVisitor.visitVarInsn(ASTORE, 3);
methodVisitor.visitVarInsn(ALOAD, 3);
methodVisitor.visitInsn(DUP);
Label label14 = new Label();
methodVisitor.visitJumpInsn(IFNULL, label14);
methodVisitor.visitTypeInsn(CHECKCAST, "java/util/Map");
methodVisitor.visitVarInsn(ASTORE, 4);
methodVisitor.visitInsn(ICONST_0);
methodVisitor.visitVarInsn(ISTORE, 5);
methodVisitor.visitVarInsn(ALOAD, 4);
methodVisitor.visitMethodInsn(INVOKEINTERFACE, "java/util/Map", "entrySet", "()Ljava/util/Set;", true);
methodVisitor.visitMethodInsn(INVOKEINTERFACE, "java/util/Set", "iterator", "()Ljava/util/Iterator;", true);
methodVisitor.visitVarInsn(ASTORE, 6);
Label label15 = new Label();
methodVisitor.visitLabel(label15);
methodVisitor.visitVarInsn(ALOAD, 6);
methodVisitor.visitMethodInsn(INVOKEINTERFACE, "java/util/Iterator", "hasNext", "()Z", true);
Label label16 = new Label();
methodVisitor.visitJumpInsn(IFEQ, label16);
methodVisitor.visitVarInsn(ALOAD, 6);
methodVisitor.visitMethodInsn(INVOKEINTERFACE, "java/util/Iterator", "next", "()Ljava/lang/Object;", true);
methodVisitor.visitTypeInsn(CHECKCAST, "java/util/Map$Entry");
methodVisitor.visitVarInsn(ASTORE, 7);
methodVisitor.visitVarInsn(ALOAD, 7);
methodVisitor.visitVarInsn(ASTORE, 8);
methodVisitor.visitInsn(ICONST_0);
methodVisitor.visitVarInsn(ISTORE, 9);
methodVisitor.visitVarInsn(ILOAD, 1);
methodVisitor.visitVarInsn(ALOAD, 8);
methodVisitor.visitMethodInsn(INVOKEINTERFACE, "java/util/Map$Entry", "getValue", "()Ljava/lang/Object;", true);
methodVisitor.visitTypeInsn(CHECKCAST, "android/graphics/Bitmap");
methodVisitor.visitMethodInsn(INVOKESTATIC, "com/bumptech/glide/util/Util", "getBitmapByteSize", "(Landroid/graphics/Bitmap;)I", false);
methodVisitor.visitInsn(IADD);
methodVisitor.visitVarInsn(ISTORE, 1);
methodVisitor.visitInsn(NOP);
methodVisitor.visitJumpInsn(GOTO, label15);
methodVisitor.visitLabel(label16);
methodVisitor.visitInsn(NOP);
methodVisitor.visitJumpInsn(GOTO, label11);
methodVisitor.visitLabel(label14);
methodVisitor.visitInsn(POP);
methodVisitor.visitInsn(NOP);
methodVisitor.visitLabel(label1);
methodVisitor.visitJumpInsn(GOTO, label11);
methodVisitor.visitLabel(label2);
methodVisitor.visitVarInsn(ASTORE, 3);
methodVisitor.visitLabel(label11);
methodVisitor.visitVarInsn(ILOAD, 1);
methodVisitor.visitInsn(IRETURN);
methodVisitor.visitMaxs(2, 10);
methodVisitor.visitEnd();
}
{
methodVisitor = classWriter.visitMethod(ACC_PUBLIC, "recycle", "()V", null, null);
methodVisitor.visitCode();
Label label0 = new Label();
Label label1 = new Label();
Label label2 = new Label();
methodVisitor.visitTryCatchBlock(label0, label1, label2, "java/lang/Throwable");
Label label3 = new Label();
Label label4 = new Label();
Label label5 = new Label();
methodVisitor.visitTryCatchBlock(label3, label4, label5, "java/lang/Throwable");
methodVisitor.visitLabel(label3);
methodVisitor.visitInsn(NOP);
methodVisitor.visitVarInsn(ALOAD, 0);
methodVisitor.visitFieldInsn(GETFIELD, "com/svga/glide/SVGAGlideResourceDelegate", "resource", "Lcom/svga/glide/SVGAResource;");
methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "com/svga/glide/SVGAResource", "getVideoItem", "()Lcom/opensource/svgaplayer/SVGAVideoEntity;", false);
methodVisitor.visitInsn(DUP);
Label label6 = new Label();
methodVisitor.visitJumpInsn(IFNULL, label6);
methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "com/opensource/svgaplayer/SVGAVideoEntity", "getImageMap$com_opensource_svgaplayer", "()Ljava/util/HashMap;", false);
Label label7 = new Label();
methodVisitor.visitJumpInsn(GOTO, label7);
methodVisitor.visitLabel(label6);
methodVisitor.visitInsn(POP);
methodVisitor.visitInsn(ACONST_NULL);
methodVisitor.visitLabel(label7);
methodVisitor.visitVarInsn(ASTORE, 1);
methodVisitor.visitFieldInsn(GETSTATIC, "com/svga/glide/SVGAGlideEx", "INSTANCE", "Lcom/svga/glide/SVGAGlideEx;");
methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "com/svga/glide/SVGAGlideEx", "getLog", "()Lcom/svga/glide/log/ILog;", false);
methodVisitor.visitVarInsn(ALOAD, 0);
methodVisitor.visitFieldInsn(GETFIELD, "com/svga/glide/SVGAGlideResourceDelegate", "TAG", "Ljava/lang/String;");
methodVisitor.visitTypeInsn(NEW, "java/lang/StringBuilder");
methodVisitor.visitInsn(DUP);
methodVisitor.visitMethodInsn(INVOKESPECIAL, "java/lang/StringBuilder", "<init>", "()V", false);
methodVisitor.visitLdcInsn("recycle ");
methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "java/lang/StringBuilder", "append", "(Ljava/lang/String;)Ljava/lang/StringBuilder;", false);
methodVisitor.visitVarInsn(ALOAD, 0);
methodVisitor.visitFieldInsn(GETFIELD, "com/svga/glide/SVGAGlideResourceDelegate", "resource", "Lcom/svga/glide/SVGAResource;");
methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "com/svga/glide/SVGAResource", "getModel", "()Ljava/lang/String;", false);
methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "java/lang/StringBuilder", "append", "(Ljava/lang/String;)Ljava/lang/StringBuilder;", false);
methodVisitor.visitLdcInsn(" size:");
methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "java/lang/StringBuilder", "append", "(Ljava/lang/String;)Ljava/lang/StringBuilder;", false);
methodVisitor.visitVarInsn(ALOAD, 1);
methodVisitor.visitInsn(DUP);
Label label8 = new Label();
methodVisitor.visitJumpInsn(IFNULL, label8);
methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "java/util/HashMap", "size", "()I", false);
methodVisitor.visitMethodInsn(INVOKESTATIC, "java/lang/Integer", "valueOf", "(I)Ljava/lang/Integer;", false);
Label label9 = new Label();
methodVisitor.visitJumpInsn(GOTO, label9);
methodVisitor.visitLabel(label8);
methodVisitor.visitInsn(POP);
methodVisitor.visitInsn(ACONST_NULL);
methodVisitor.visitLabel(label9);
methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "java/lang/StringBuilder", "append", "(Ljava/lang/Object;)Ljava/lang/StringBuilder;", false);
methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "java/lang/StringBuilder", "toString", "()Ljava/lang/String;", false);
methodVisitor.visitMethodInsn(INVOKEINTERFACE, "com/svga/glide/log/ILog", "d", "(Ljava/lang/String;Ljava/lang/String;)V", true);
methodVisitor.visitVarInsn(ALOAD, 1);
methodVisitor.visitInsn(DUP);
Label label10 = new Label();
methodVisitor.visitJumpInsn(IFNULL, label10);
methodVisitor.visitTypeInsn(CHECKCAST, "java/util/Map");
methodVisitor.visitVarInsn(ASTORE, 2);
methodVisitor.visitInsn(ICONST_0);
methodVisitor.visitVarInsn(ISTORE, 3);
methodVisitor.visitVarInsn(ALOAD, 2);
methodVisitor.visitMethodInsn(INVOKEINTERFACE, "java/util/Map", "entrySet", "()Ljava/util/Set;", true);
methodVisitor.visitMethodInsn(INVOKEINTERFACE, "java/util/Set", "iterator", "()Ljava/util/Iterator;", true);
methodVisitor.visitVarInsn(ASTORE, 4);
Label label11 = new Label();
methodVisitor.visitLabel(label11);
methodVisitor.visitVarInsn(ALOAD, 4);
methodVisitor.visitMethodInsn(INVOKEINTERFACE, "java/util/Iterator", "hasNext", "()Z", true);
Label label12 = new Label();
methodVisitor.visitJumpInsn(IFEQ, label12);
methodVisitor.visitVarInsn(ALOAD, 4);
methodVisitor.visitMethodInsn(INVOKEINTERFACE, "java/util/Iterator", "next", "()Ljava/lang/Object;", true);
methodVisitor.visitTypeInsn(CHECKCAST, "java/util/Map$Entry");
methodVisitor.visitVarInsn(ASTORE, 5);
methodVisitor.visitVarInsn(ALOAD, 5);
methodVisitor.visitVarInsn(ASTORE, 6);
methodVisitor.visitInsn(ICONST_0);
methodVisitor.visitVarInsn(ISTORE, 7);
methodVisitor.visitFieldInsn(GETSTATIC, "com/svga/glide/SVGAGlideEx", "INSTANCE", "Lcom/svga/glide/SVGAGlideEx;");
methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "com/svga/glide/SVGAGlideEx", "getBitmapPool", "()Lcom/bumptech/glide/load/engine/bitmap_recycle/BitmapPool;", false);
methodVisitor.visitVarInsn(ALOAD, 6);
methodVisitor.visitMethodInsn(INVOKEINTERFACE, "java/util/Map$Entry", "getValue", "()Ljava/lang/Object;", true);
methodVisitor.visitTypeInsn(CHECKCAST, "android/graphics/Bitmap");
methodVisitor.visitMethodInsn(INVOKEINTERFACE, "com/bumptech/glide/load/engine/bitmap_recycle/BitmapPool", "put", "(Landroid/graphics/Bitmap;)V", true);
methodVisitor.visitInsn(NOP);
methodVisitor.visitJumpInsn(GOTO, label11);
methodVisitor.visitLabel(label12);
methodVisitor.visitInsn(NOP);
Label label13 = new Label();
methodVisitor.visitJumpInsn(GOTO, label13);
methodVisitor.visitLabel(label10);
methodVisitor.visitInsn(POP);
methodVisitor.visitInsn(NOP);
methodVisitor.visitLabel(label4);
methodVisitor.visitJumpInsn(GOTO, label13);
methodVisitor.visitLabel(label5);
methodVisitor.visitVarInsn(ASTORE, 1);
methodVisitor.visitLabel(label0);
methodVisitor.visitInsn(NOP);
methodVisitor.visitVarInsn(ALOAD, 0);
methodVisitor.visitFieldInsn(GETFIELD, "com/svga/glide/SVGAGlideResourceDelegate", "resource", "Lcom/svga/glide/SVGAResource;");
methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "com/svga/glide/SVGAResource", "getImageMapField", "()Lcom/svga/glide/util/ReflectUtils;", false);
methodVisitor.visitInsn(DUP);
Label label14 = new Label();
methodVisitor.visitJumpInsn(IFNULL, label14);
methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "com/svga/glide/util/ReflectUtils", "get", "()Ljava/lang/Object;", false);
methodVisitor.visitTypeInsn(CHECKCAST, "java/util/HashMap");
Label label15 = new Label();
methodVisitor.visitJumpInsn(GOTO, label15);
methodVisitor.visitLabel(label14);
methodVisitor.visitInsn(POP);
methodVisitor.visitInsn(ACONST_NULL);
methodVisitor.visitLabel(label15);
methodVisitor.visitVarInsn(ASTORE, 2);
methodVisitor.visitFieldInsn(GETSTATIC, "com/svga/glide/SVGAGlideEx", "INSTANCE", "Lcom/svga/glide/SVGAGlideEx;");
methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "com/svga/glide/SVGAGlideEx", "getLog", "()Lcom/svga/glide/log/ILog;", false);
methodVisitor.visitVarInsn(ALOAD, 0);
methodVisitor.visitFieldInsn(GETFIELD, "com/svga/glide/SVGAGlideResourceDelegate", "TAG", "Ljava/lang/String;");
methodVisitor.visitTypeInsn(NEW, "java/lang/StringBuilder");
methodVisitor.visitInsn(DUP);
methodVisitor.visitMethodInsn(INVOKESPECIAL, "java/lang/StringBuilder", "<init>", "()V", false);
methodVisitor.visitLdcInsn("recycle ");
methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "java/lang/StringBuilder", "append", "(Ljava/lang/String;)Ljava/lang/StringBuilder;", false);
methodVisitor.visitVarInsn(ALOAD, 0);
methodVisitor.visitFieldInsn(GETFIELD, "com/svga/glide/SVGAGlideResourceDelegate", "resource", "Lcom/svga/glide/SVGAResource;");
methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "com/svga/glide/SVGAResource", "getModel", "()Ljava/lang/String;", false);
methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "java/lang/StringBuilder", "append", "(Ljava/lang/String;)Ljava/lang/StringBuilder;", false);
methodVisitor.visitLdcInsn(" size:");
methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "java/lang/StringBuilder", "append", "(Ljava/lang/String;)Ljava/lang/StringBuilder;", false);
methodVisitor.visitVarInsn(ALOAD, 2);
methodVisitor.visitInsn(DUP);
Label label16 = new Label();
methodVisitor.visitJumpInsn(IFNULL, label16);
methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "java/util/HashMap", "size", "()I", false);
methodVisitor.visitMethodInsn(INVOKESTATIC, "java/lang/Integer", "valueOf", "(I)Ljava/lang/Integer;", false);
Label label17 = new Label();
methodVisitor.visitJumpInsn(GOTO, label17);
methodVisitor.visitLabel(label16);
methodVisitor.visitInsn(POP);
methodVisitor.visitInsn(ACONST_NULL);
methodVisitor.visitLabel(label17);
methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "java/lang/StringBuilder", "append", "(Ljava/lang/Object;)Ljava/lang/StringBuilder;", false);
methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "java/lang/StringBuilder", "toString", "()Ljava/lang/String;", false);
methodVisitor.visitMethodInsn(INVOKEINTERFACE, "com/svga/glide/log/ILog", "d", "(Ljava/lang/String;Ljava/lang/String;)V", true);
methodVisitor.visitVarInsn(ALOAD, 2);
methodVisitor.visitInsn(DUP);
Label label18 = new Label();
methodVisitor.visitJumpInsn(IFNULL, label18);
methodVisitor.visitTypeInsn(CHECKCAST, "java/util/Map");
methodVisitor.visitVarInsn(ASTORE, 3);
methodVisitor.visitInsn(ICONST_0);
methodVisitor.visitVarInsn(ISTORE, 4);
methodVisitor.visitVarInsn(ALOAD, 3);
methodVisitor.visitMethodInsn(INVOKEINTERFACE, "java/util/Map", "entrySet", "()Ljava/util/Set;", true);
methodVisitor.visitMethodInsn(INVOKEINTERFACE, "java/util/Set", "iterator", "()Ljava/util/Iterator;", true);
methodVisitor.visitVarInsn(ASTORE, 5);
Label label19 = new Label();
methodVisitor.visitLabel(label19);
methodVisitor.visitVarInsn(ALOAD, 5);
methodVisitor.visitMethodInsn(INVOKEINTERFACE, "java/util/Iterator", "hasNext", "()Z", true);
Label label20 = new Label();
methodVisitor.visitJumpInsn(IFEQ, label20);
methodVisitor.visitVarInsn(ALOAD, 5);
methodVisitor.visitMethodInsn(INVOKEINTERFACE, "java/util/Iterator", "next", "()Ljava/lang/Object;", true);
methodVisitor.visitTypeInsn(CHECKCAST, "java/util/Map$Entry");
methodVisitor.visitVarInsn(ASTORE, 6);
methodVisitor.visitVarInsn(ALOAD, 6);
methodVisitor.visitVarInsn(ASTORE, 7);
methodVisitor.visitInsn(ICONST_0);
methodVisitor.visitVarInsn(ISTORE, 8);
methodVisitor.visitFieldInsn(GETSTATIC, "com/svga/glide/SVGAGlideEx", "INSTANCE", "Lcom/svga/glide/SVGAGlideEx;");
methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "com/svga/glide/SVGAGlideEx", "getBitmapPool", "()Lcom/bumptech/glide/load/engine/bitmap_recycle/BitmapPool;", false);
methodVisitor.visitVarInsn(ALOAD, 7);
methodVisitor.visitMethodInsn(INVOKEINTERFACE, "java/util/Map$Entry", "getValue", "()Ljava/lang/Object;", true);
methodVisitor.visitTypeInsn(CHECKCAST, "android/graphics/Bitmap");
methodVisitor.visitMethodInsn(INVOKEINTERFACE, "com/bumptech/glide/load/engine/bitmap_recycle/BitmapPool", "put", "(Landroid/graphics/Bitmap;)V", true);
methodVisitor.visitInsn(NOP);
methodVisitor.visitJumpInsn(GOTO, label19);
methodVisitor.visitLabel(label20);
methodVisitor.visitInsn(NOP);
methodVisitor.visitJumpInsn(GOTO, label13);
methodVisitor.visitLabel(label18);
methodVisitor.visitInsn(POP);
methodVisitor.visitInsn(NOP);
methodVisitor.visitLabel(label1);
methodVisitor.visitJumpInsn(GOTO, label13);
methodVisitor.visitLabel(label2);
methodVisitor.visitVarInsn(ASTORE, 2);
methodVisitor.visitLabel(label13);
methodVisitor.visitVarInsn(ALOAD, 0);
methodVisitor.visitFieldInsn(GETFIELD, "com/svga/glide/SVGAGlideResourceDelegate", "resource", "Lcom/svga/glide/SVGAResource;");
methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "com/svga/glide/SVGAResource", "getVideoItem", "()Lcom/opensource/svgaplayer/SVGAVideoEntity;", false);
methodVisitor.visitInsn(DUP);
Label label21 = new Label();
methodVisitor.visitJumpInsn(IFNONNULL, label21);
methodVisitor.visitInsn(POP);
Label label22 = new Label();
methodVisitor.visitJumpInsn(GOTO, label22);
methodVisitor.visitLabel(label21);
methodVisitor.visitInsn(ACONST_NULL);
methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "com/opensource/svgaplayer/SVGAVideoEntity", "setMovieItem", "(Lcom/opensource/svgaplayer/proto/MovieEntity;)V", false);
methodVisitor.visitLabel(label22);
methodVisitor.visitVarInsn(ALOAD, 0);
methodVisitor.visitFieldInsn(GETFIELD, "com/svga/glide/SVGAGlideResourceDelegate", "resource", "Lcom/svga/glide/SVGAResource;");
methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "com/svga/glide/SVGAResource", "getVideoItem", "()Lcom/opensource/svgaplayer/SVGAVideoEntity;", false);
methodVisitor.visitInsn(DUP);
Label label23 = new Label();
methodVisitor.visitJumpInsn(IFNULL, label23);
methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "com/opensource/svgaplayer/SVGAVideoEntity", "clear", "()V", false);
Label label24 = new Label();
methodVisitor.visitJumpInsn(GOTO, label24);
methodVisitor.visitLabel(label23);
methodVisitor.visitInsn(POP);
methodVisitor.visitLabel(label24);
methodVisitor.visitInsn(RETURN);
methodVisitor.visitMaxs(5, 9);
methodVisitor.visitEnd();
}
{
methodVisitor = classWriter.visitMethod(ACC_PUBLIC | ACC_BRIDGE | ACC_SYNTHETIC, "get", "()Ljava/lang/Object;", null, null);
methodVisitor.visitCode();
methodVisitor.visitVarInsn(ALOAD, 0);
methodVisitor.visitMethodInsn(INVOKEVIRTUAL, "com/svga/glide/SVGAGlideResourceDelegate", "get", "()Lcom/svga/glide/SVGAResource;", false);
methodVisitor.visitInsn(ARETURN);
methodVisitor.visitMaxs(1, 1);
methodVisitor.visitEnd();
}
classWriter.visitEnd();

return classWriter.toByteArray();
}
}

Process finished with exit code 0
